name: Security Checks
on:
  push:
    branches: [ main ]
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Snyk vulnerability scan on backend
        uses: snyk/actions@master
        with:
          args: test sec-forum-backend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Monitor backend project with Snyk
        uses: snyk/actions@master
        with:
          args: monitor sec-forum-backend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk vulnerability scan on frontend
        uses: snyk/actions@master
        with:
          args: test sec-forum-frontend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Monitor frontend project with Snyk
        uses: snyk/actions@master
        with:
          args: monitor sec-forum-frontend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk Code test on backend
        uses: snyk/actions@master
        with:
          args: code test sec-forum-backend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk Code test on frontend
        uses: snyk/actions@master
        with:
          args: code test sec-forum-frontend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
