name: Security Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  snyk-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Snyk Test for Backend
      - name: Run Snyk vulnerability scan on backend
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: sec-forum-backend

      # Snyk Monitor for Backend
      - name: Monitor backend project with Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: sec-forum-backend

      # Snyk Code Test for Backend
      - name: Run Snyk Code test on backend
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: sec-forum-backend

  snyk-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Snyk Test for Frontend
      - name: Run Snyk vulnerability scan on frontend
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: sec-forum-frontend

      # Snyk Monitor for Frontend
      - name: Monitor frontend project with Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: sec-forum-frontend

      # Snyk Code Test for Frontend
      - name: Run Snyk Code test on frontend
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: sec-forum-frontend
